// Booking Form Submission
function attachFormListeners() {
  const bookingForm = document.getElementById('bookingForm');
    if (bookingForm) {
        bookingForm.addEventListener('submit', (e) => {
              e.preventDefault();
                    const form = e.target;
                          const formMessage = document.getElementById('formMessage');

                                const name = form.querySelector('#name').value;
                                      const email = form.querySelector('#email').value;
                                            const device = form.querySelector('#device').value;
                                                  const issue = form.querySelector('#issue').value;

                                                        // WhatsApp URL-based submission
                                                              const message = `Booking Request:\nName: ${name}\nEmail: ${email}\nDevice: ${device}\nIssue: ${issue}`;
                                                                    const phoneNumber = '+34666666666'; // Replace with your WhatsApp Business number (e.g., +919876543210)
                                                                          const whatsappUrl = `https://wa.me/${phoneNumber}?text=${encodeURIComponent(message)}`;

                                                                                // Open WhatsApp link
                                                                                      window.open(whatsappUrl, '_blank');

                                                                                            // Show success message
                                                                                                  formMessage.innerHTML = '<p style="color: #10B981;">Thank you for your booking! Please send the WhatsApp message to confirm.</p>';
                                                                                                        form.reset();
                                                                                                            });
                                                                                                              }

                                                                                                                const postalCodeForm = document.getElementById('postalCodeForm');
                                                                                                                  if (postalCodeForm) {
                                                                                                                      postalCodeForm.addEventListener('submit', (e) => {
                                                                                                                            e.preventDefault();
                                                                                                                                  const form = e.target;
                                                                                                                                        const postalCodeMessage = document.getElementById('postalCodeMessage');
                                                                                                                                              const postalCode = form.querySelector('#postalCode').value;

                                                                                                                                                    // Simulated check (replace with actual postal codes)
                                                                                                                                                          const validCodes = ['110001', '110002', '110003'];
                                                                                                                                                                const message = validCodes.includes(postalCode)
                                                                                                                                                                        ? `Great news! We service your area (Postal Code: ${postalCode}). Book now!`
                                                                                                                                                                                : `We’re sorry, we don’t service postal code ${postalCode} yet. Contact us for assistance.`;

                                                                                                                                                                                      // WhatsApp URL-based submission
                                                                                                                                                                                            const whatsappMessage = `Postal Code Check:\nPostal Code: ${postalCode}\nResult: ${message}`;
                                                                                                                                                                                                   const phoneNumber = '+34666666666'; // Replace with your WhatsApp Business number
                                                                                                                                                                                                        const whatsappUrl = `https://wa.me/${phoneNumber}?text=${encodeURIComponent(whatsappMessage)}`;

                                                                                                                                                                                                              // Open WhatsApp link
                                                                                                                                                                                                                    window.open(whatsappUrl, '_blank');

                                                                                                                                                                                                                          // Show message
                                                                                                                                                                                                                                postalCodeMessage.innerHTML = `<p style="color: ${validCodes.includes(postalCode) ? '#10B981' : '#EF4444'}">${message}</p>`;
                                                                                                                                                                                                                                      form.reset();
                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                            // Background Particle Animation (Tron-Inspired)
                                                                                                                                                                                                                                            function createParticles() {
                                                                                                                                                                                                                                              const canvas = document.createElement('canvas');
                                                                                                                                                                                                                                                canvas.style.position = 'fixed';
                                                                                                                                                                                                                                                  canvas.style.top = '0';
                                                                                                                                                                                                                                                    canvas.style.left = '0';
                                                                                                                                                                                                                                                      canvas.style.width = '100%';
                                                                                                                                                                                                                                                        canvas.style.height = '100%';
                                                                                                                                                                                                                                                          canvas.style.zIndex = '-1';
                                                                                                                                                                                                                                                            canvas.style.pointerEvents = 'none';
                                                                                                                                                                                                                                                              document.body.appendChild(canvas);

                                                                                                                                                                                                                                                                const ctx = canvas.getContext('2d');
                                                                                                                                                                                                                                                                  canvas.width = window.innerWidth;
                                                                                                                                                                                                                                                                    canvas.height = window.innerHeight;

                                                                                                                                                                                                                                                                      const particles = [];
                                                                                                                                                                                                                                                                        const particleCount = 50;

                                                                                                                                                                                                                                                                          for (let i = 0; i < particleCount; i++) {
                                                                                                                                                                                                                                                                              particles.push({
                                                                                                                                                                                                                                                                                    x: Math.random() * canvas.width,
                                                                                                                                                                                                                                                                                          y: Math.random() * canvas.height,
                                                                                                                                                                                                                                                                                                radius: Math.random() * 2 + 1,
                                                                                                                                                                                                                                                                                                      speedX: Math.random() * 0.5 - 0.25,
                                                                                                                                                                                                                                                                                                            speedY: Math.random() * 0.5 - 0.25,
                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                    function animate() {
                                                                                                                                                                                                                                                                                                                        ctx.clearRect(0, 0, canvas.width, canvas.height);
                                                                                                                                                                                                                                                                                                                            ctx.fillStyle = 'rgba(167, 139, 250, 0.5)';
                                                                                                                                                                                                                                                                                                                                particles.forEach((particle) => {
                                                                                                                                                                                                                                                                                                                                      ctx.beginPath();
                                                                                                                                                                                                                                                                                                                                            ctx.arc(particle.x, particle.y, particle.radius, 0, Math.PI * 2);
                                                                                                                                                                                                                                                                                                                                                  ctx.fill();
                                                                                                                                                                                                                                                                                                                                                        particle.x += particle.speedX;
                                                                                                                                                                                                                                                                                                                                                              particle.y += particle.speedY;

                                                                                                                                                                                                                                                                                                                                                                    if (particle.x < 0 || particle.x > canvas.width) particle.speedX *= -1;
                                                                                                                                                                                                                                                                                                                                                                          if (particle.y < 0 || particle.y > canvas.height) particle.speedY *= -1;
                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                  requestAnimationFrame(animate);
                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                      animate();
                                                                                                                                                                                                                                                                                                                                                                                        window.addEventListener('resize', () => {
                                                                                                                                                                                                                                                                                                                                                                                            canvas.width = window.innerWidth;
                                                                                                                                                                                                                                                                                                                                                                                                canvas.height = window.innerHeight;
                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                  // Wait for DOM to load and React to render
                                                                                                                                                                                                                                                                                                                                                                                                  document.addEventListener('DOMContentLoaded', () => {
                                                                                                                                                                                                                                                                                                                                                                                                    // Delay to ensure React renders forms
                                                                                                                                                                                                                                                                                                                                                                                                      setTimeout(attachFormListeners, 1000);
                                                                                                                                                                                                                                                                                                                                                                                                        createParticles();
                                                                                                                                                                                                                                                                                                                                                                                                        });